### ISSUE TITLE
Make a noarch version of the recipe

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/pybind11-feedstock#1]
When we have an answer to conda/conda#2456, we will probably be able to have a `noarch_python` version of that recipe.

**Comment by pelson** [comment]
Ping me when you want to move this forwards. We will probably want to update the CI scripts to deal with  noarch. Some thought is needed in terms of testing - e.g. how do we assert that a noarch package works on all platforms, yet only upload from one?

**Comment by wjakob** [comment]
@pelson: any time is fine. What do you need us to do? Is it better to wait for a new release of the package?

**Comment by SylvainCorlay** [comment]
It seems that it depends on https://github.com/conda/conda-build/issues/934

**Comment by SylvainCorlay** [comment]
Closing, I don't think that this will ever be resolved upstream anyway, and it is fine to have extra builds for 64 and 32 bit architectures.
