### ISSUE TITLE
pybind11-global is noarch: python, but installs python minor-version specific version of the headers

### ISSUE THREAD

**Issue by traversaro** [conda-forge/pybind11-feedstock#107]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

PR https://github.com/conda-forge/pybind11-feedstock/pull/84 changed the `pybind11-global` package in to be a `noarch: python` package, but it seems that contains headers that are installed in `include/python3.13/`, see https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fnoarch%2Fpybind11-global-2.13.6-pyh085cc03_1.conda .

### Installed packages

pybind11-global-2.13.6-pyh085cc03_1

### Environment info

.

**Comment by isuruf** [comment]
I'm not sure why we have the headers duplicated in `include/pybind11` and `include/python3.13/pybind11_global/pybind11`

**Comment by henryiii** [comment]
The "global" package installs both, we don't break it up further. We could just delete the python specific ones here, perhaps?
