### ISSUE TITLE
distutils style vs CMake style installation

### ISSUE THREAD

**Issue by loriab** [conda-forge/pybind11-feedstock#11]
Would you consider reformulating the recipe so that it pulls from GitHub and "builds" and installs with CMake? That way the directory structure would be more standard (`include/pybind` instead of `include/python3.5m/pybind`) and some extra files would get installed (e.g. `pybind11Config.cmake`). I think users of a C++ template library would expect more of a GNU project than python project layout. Up to you, of course, I don't mean to be pybind11's resident CMake nag.

I'm glad to help on the recipe if you're interested in making the change.

**Comment by SylvainCorlay** [comment]
@loriab this should be fixed now.

**Comment by SylvainCorlay** [comment]
So

 - the headers are placed in the same directory as before and people who use distutils as a build tool should not have their workflow broken.
 - but the `pybind11Config.cmake` file is generated properly and points to that very same location.
