### ISSUE TITLE
Headers not installed on Python 2.7

### ISSUE THREAD

**Issue by dfm** [conda-forge/pybind11-feedstock#15]
I'm not sure if this is the right place to open this issue but I don't have any problem when I install using pip or from source. My apologies if this should be opened elsewhere.

All of my Python 2.7 builds on travis just started failing because it looks like this recipe no longer installs the pybind11 headers in the expected place (or anywhere, as far as I can tell!). I've tested on my own machine and I find the same behavior. Everything is there when I install using conda-forge and Python 3.x but not on Python 2.7.

I expect that this has something to do with the recent switch to the CMake build but I haven't been able to track down the culprit.

Thanks!

**Comment by wjakob** [comment]
^ @SylvainCorlay

**Comment by SylvainCorlay** [comment]
on it.

**Comment by SylvainCorlay** [comment]
I can reproduce, and the circleci log show that on python2.7, headers don't get installed.

**Comment by SylvainCorlay** [comment]
SO the issue is the on (linux + python2.7), pybind11's `FindPythonLibsNew` returns the another python install than the current one.

**Comment by SylvainCorlay** [comment]
OK, just need to explicitly specify the path to python executable. PR coming.

**Comment by SylvainCorlay** [comment]
@dfm the package is up on anaconda for linux platforms.

Unfortunately, there is some backlog on windows and OS X, so it is going to take a little bit of time before your travis turns green again.

**Comment by dfm** [comment]
I can confirm that this now works again on Mac and Unix. The Windows build still hasn't propagated but it wasn't a problem before so I'm going to close this. Thanks for this!
