### ISSUE TITLE
Feedstock issues

### ISSUE THREAD

**Issue by wjakob** [conda-forge/pybind11-feedstock#20]
After deploying the latest pybind11 version in the feedstock, there seem to be some issues with the CI bots.

The CircleCI bot did not pick up the new revision, and I can't seem to find out how to trigger it manually. AppVeyor has been in "queued" mode for hours -- I assume that it will be picked up eventually.

**Comment by wjakob** [comment]
^ @SylvainCorlay

**Comment by dean0x7d** [comment]
It's possible that the feedstock needs to be rerendered for a newer `conda-smithy`.
