### ISSUE TITLE
unresolved external symbol __imp_strdup referenced in function "protected: void __cdecl pybind11::cpp_function::initialize_generic(...)

### ISSUE THREAD

**Issue by looooo** [conda-forge/pybind11-feedstock#23]
I am trying to compile an aplication for windows which uses pybind11. Now I am struggeling with this problem. I don't know if this is related to my code, the conda package of pybind11 or pybind11 itself. Maybe someone has an idea what the source of this problem is...

```MeshFlatteningPy.cpp.obj : error LNK2019: unresolved external symbol __imp_strdup referenced in function "protected: void __cdecl pybind11::cpp_function::initialize_generic(struct pybind11::detail::function_record *,char const *,class type_info const * const *,unsigned __int64)" (?initialize_generic@cpp_function@pybind11@@IEAAXPEAUfunction_record@detail@2@PEBDPEBQEBVtype_info@@_K@Z)```

**Comment by wjakob** [comment]
Closing the issue here, this bug tracker is only for feedstock-related issues.
