### ISSUE TITLE
Win32/win64 versions of packages?

### ISSUE THREAD

**Issue by wjakob** [conda-forge/pybind11-feedstock#3]
After updating the feedstock recipe, I saw that the builds are automatically uploaded here: https://anaconda.org/conda-forge/pybind11/files

However, the win-32 and win-64 versions are no longer added. Does this mean that windows users can't use pybind11 v1.8 via conda now?

This is likely related to issue #1.

**Comment by wjakob** [comment]
cc @SylvainCorlay

**Comment by SylvainCorlay** [comment]
I don't know what is going on here. However, I heard that it is not recommended to push to master on a feedstock , and that one should rather open a PR.

**Comment by SylvainCorlay** [comment]
@pelson @jakirkham any clue what is going on here?

**Comment by jakirkham** [comment]
@pelson is out. I think AppVeyor just didn't run. Have restarted it.

**Comment by jakirkham** [comment]
So, everything appears to have passed and deployed except Windows Python 3.5 32-bit. This appears to be an error downloading something. As AppVeyor does not have a way to build one element of a matrix (or perhaps I don't know how), I retriggered a full build. However, we have a bit of a backlog. So it may be a bit before we see that build.

**Comment by wjakob** [comment]
Closing this, as the windows builds got deployed in the end -- thank you for looking into this!
