### ISSUE TITLE
install with both cmake and setuptools

### ISSUE THREAD

**Issue by roeey777** [conda-forge/pybind11-feedstock#51]
Hi
I have a question about pybind11, why in the `build.sh` pybind11 is installed via `cmake` **and** `setuptools`?
both of them installs the same headers to different locations
- `cmake` installs the headers to `$PREFIX/include` and the `*Config.cmake` files to `$PREFIX/share/cmake/pybind11`
- `python setuptools` install the headers to `$PREFIX/include/python<major.minor>/site-packages/pybind11/include/pybind11`

Why both of them are needed?
- If I choose to build using`cmake` then I will surly use `find_package(Python REQUIRED)` and then I will have all the headers located within `python` include directory (because of the setuptools installation) which makes the pure `cmake` installation redundant (there is no need to `find_package(pybind11 REQUIRED)`).
- If I choose to build using `setuptools` then I surely don't need any of the `*Config.cmake` files.

`python` is obviously installed when working with `pybind11` so is there any reason to prefer `cmake` build over `setuptools`?

I would like to know the rational behind installing `pybind11` with both solutions since I want to add this awesome library to `buildroot` and I want to understand if I need to port both installation solutions in order to install `pybind11` properly.
I'm looking forward to use `pybind11` in my embedded linux projects!

**Comment by ax3l** [comment]
> If I choose to build usingcmake then I will surly use find_package(Python REQUIRED) and then I will have all the headers located within python include directory

Not necessarily, I don't do that. CMake is needed because people downstream might search for the header-only library pybind11 from a C++ project via `find_package(pybind11)`. If you don't install via CMake, the config package is missing.

**Comment by henryiii** [comment]
This will be handled by setuptools directly soon, hopefully. See https://github.com/pybind/pybind11/pull/2433 which adds this.

**Comment by henryiii** [comment]
This was resolved with 2.6.0.
