### ISSUE TITLE
globally pin the pybind11 versions

### ISSUE THREAD

**Issue by beckermr** [conda-forge/pybind11-feedstock#53]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

We got a report from @bluescarni (see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/849#issuecomment-706235110) that different pybind11 versions generate python libraries which are not interoperable between one another. 

Assuming this is, in fact, true, we plan to globally pin the version of pybind11 for all of conda-forge. See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/849. This will ease the maintenance burden for users who want to use different packages together and don't want to run around updating pins in recipes. 

cc @conda-forge/core @conda-forge/pybind11

**Comment by henryiii** [comment]
This should only change when the internal ABI string changes. The string last changed for 2.4, I believe. Also, keep in mind that many (most?) packages internally pin pybind11, by submodule (in git) and including the headers in the SDist.

**Comment by beckermr** [comment]
> This should only change when the internal ABI string changes.

What are you referring to? The pin?
